version: '3.1'

services:

    adminer:
        image: adminer
        restart: always
        ports:
            - 80:8080

    dbMysql:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: foodiefix
